---
#title: "About / FAQ"
menu: main
---

```{r, include=FALSE}
library(tidyverse)
library(readxl)

knitr::opts_chunk$set(echo=FALSE, message = FALSE, warning = FALSE)

content_timeline <- read_csv(here::here("data", "timeline.csv")) %>% 
  mutate(side = if_else((row_number() %% 2) == 0, "right", "left"))  #column that alternates between left and right

content_faq <- read_csv(here::here("data", "faq.csv"))
```

## How the project began

```{r, results='asis'}
generate_timeline_row <- function(time, text, side, size){
  cat('<div class="row">')
  
  if(side == "left"){
    cat('<div class="col-sm-5">')
    cat(str_c('<h3 class=', size, '>', time, '</h3>'))
    cat(str_c('<p>', text, '</p>'))
    cat('</div>')
    
    cat('<div class="col-sm-2">')
    cat('<div style="text-align:center"><span class="dot ', size, '"></span></div>')
    cat('</div>')
    
    cat('<div class="col-sm-5">')
    cat('</div>')
  } else {
    cat('<div class="col-sm-5">')
    cat('</div>')
    
    cat('<div class="col-sm-2">')
    cat('<div style="text-align:center"><span class="dot ', size, '"></span></div>')
    cat('</div>')
    
    cat('<div class="col-sm-5">')
    cat(str_c('<h3 class=', size, '>', time, '</h3>'))
    cat(str_c('<p>', text, '</p>'))
    cat('</div>')
  }
  
  cat('</div>')
}

cat('<div class="timeline">')
content_timeline %>% 
  select(time, text, side, size) %>% 
  pwalk(generate_timeline_row)
cat('<div class="arrow"></div>') #draw arrow
cat('</div>')
```

<div class="faq">

## Help / FAQ
```{r, results='asis'}
generate_faq <- function(question, answer){
  cat(str_c('<h4 class="faq-question">', question, '</h4>'))
  cat(str_c('<p class="faq-answer">', answer, '</p>'))
}

cat('<div class="faq-content text-center">')
content_faq %>% 
  pwalk(generate_faq)
cat('</div>')
```

</div>